coverage:
  status:
    project:
      default:
        informational: true
    patch:
      default:
        informational: true
comment:
  require_changes: yes
  branches:               # branch names that can post comment
    - "master"