name: Lint

on: [push, pull_request]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8] #3.7, 3.8
      
    runs-on: ubuntu-latest
    
    name: pylint with Py ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install --no-dev
        poetry install -E pylint
    - name: Run pylint
      run: |
        poetry run pylint --version
        ls
        find bovheat_src/ -type f -name "*.py" | xargs poetry run pylint --fail-under 7